problem: https://adventofcode.com/2024/day/14

In [1]:
import numpy as np
import os

In [25]:
data = []
problem_number = 14
path = os.path.join('..', 'data', f'problem{problem_number}_data.txt')
with open(path, 'r') as file:
    for line in file:
        line = line.strip().split()
        p, v = line[0][2:].split(','), line[1][2:].split(',')
        data.append((np.array(p, dtype=int), np.array(v, dtype=int)))

In [40]:
SPACE_SIZE = (101, 103)
ITERATIONS = 100
space = np.full(SPACE_SIZE, 0)

In [41]:
space

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(101, 103))

In [42]:
for p, v in data:
    x = p + v*ITERATIONS
    i = x[0] % SPACE_SIZE[0]
    j = x[1] % SPACE_SIZE[1]
    space[i, j] += 1

In [49]:
q1 = space[:SPACE_SIZE[0]//2, :SPACE_SIZE[1]//2]
q2 = space[1 + SPACE_SIZE[0]//2:, :SPACE_SIZE[1]//2]
q3 = space[:SPACE_SIZE[0]//2, 1 + SPACE_SIZE[1]//2:]
q4 = space[1 + SPACE_SIZE[0]//2:, 1 + SPACE_SIZE[1]//2:]

In [50]:
solution = q1.sum() * q2.sum() * q3.sum() * q4.sum()
print(f'{solution = }')

solution = np.int64(223020000)


**Part 2**

In [96]:
positions = []
velocities = []
for p, v in data:
    positions.append(p)
    velocities.append(v)

In [97]:
def move_robots(positions, velocities=velocities, space_size=SPACE_SIZE):
    space = np.full(space_size, 0)
    result = []
    for p, v in zip(positions, velocities):
        x = (p + v) % space_size
        result.append(x)
        space[x[0], x[1]] = 1
    return result, space   

In [ ]:
go = True
k = 0
while go:
    k += 1
    positions, space = move_robots(positions)
    space = space.T
    for i in range(space.shape[0]-2):
        for j in range(2, space.shape[1] - 2):
            if (space[i, j] == 1 and
                space[i, j-1] == 0 and
                space[i, j+1] == 0 and
                space[i+1, j] == 1 and
                space[i+1, j-1] == 1 and
                space[i+1, j+1] == 1 and
                space[i+2, j] == 1 and
                space[i+2, j-2] == 1 and
                space[i+2, j-1] == 1 and
                space[i+2, j+2] == 1 and
                space[i+2, j+1] == 1):
                print(k)
                go = False
                print(space)
    if k == 103*101:
        go = False    

7338
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [102]:
for r in space:
    row = ''
    for i in r:
        if i==0:
            row += '.'
        else:
            row += '#'
    print(row)

.....................................................................................................
.......#.............................................................................................
...................#....#.#..........................................................................
.................................................................................#...................
............................................#.........#....#.........................................
................................#....................................................................
..................#..................................................................................
...#.......................................................................#.........................
...............................................................#.....................................
..................#...................................#............#..............